# Site settings
title:          "Random Posts"
description:    "A Simple Blog to ..."
baseurl:        "/randomposts"
url:            "https://vijaypolimeru.github.io/Something_Abt_Everything"

# Google Analytics
google_analytics: UA-148011093-1

# Author
author:
  name:         Vijay Kumar Polimeru
  url:          https://vijaypolimeru.github.io
  email:        vijaypolimeru@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed


  
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme  
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         vijaypolimeru-github-io

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5  